# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-08 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20180806_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='created',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='post',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='updated',
        ),
        migrations.AddField(
            model_name='questions',
            name='AF',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='CVD',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='DM',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='LVH',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='SBP',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='SBP_treatment',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='add_question2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='sleep',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questions',
            name='smoker',
            field=models.IntegerField(),
        ),
    ]
