# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-08 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_auto_20180808_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='add_question2',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='sleep',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
