# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-08 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_auto_20180808_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='SBP',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='sex',
            field=models.IntegerField(),
        ),
    ]
