# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-09 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_auto_20180808_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='AF',
            field=models.IntegerField(db_column='AF'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='CVD',
            field=models.IntegerField(db_column='CVD'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='DM',
            field=models.IntegerField(db_column='DM'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='LVH',
            field=models.IntegerField(db_column='LVH'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='SBP',
            field=models.IntegerField(db_column='SBP'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='SBP_treatment',
            field=models.IntegerField(db_column='SBP_tr'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='add_question2',
            field=models.IntegerField(db_column='question', default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questions',
            name='age',
            field=models.IntegerField(db_column='age'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='sex',
            field=models.IntegerField(db_column='sex'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='sleep',
            field=models.IntegerField(db_column='sleep', default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questions',
            name='smoker',
            field=models.IntegerField(db_column='smoker'),
        ),
    ]
